# Generated by Django 3.1.7 on 2021-03-01 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210228_0926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritenews',
            options={'verbose_name': 'Favorite news'},
        ),
        migrations.AlterUniqueTogether(
            name='favouritenews',
            unique_together={('user', 'news')},
        ),
    ]
