# Generated by Django 3.1.7 on 2021-03-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210228_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Контакты'},
        ),
    ]
